fix non breaking security vulnerabilities (#33)
* added make targets to interact with npm

* add optional args to other commands

* reduced vulnerabilites via npm audit fix (622 to 512)

* ran npm audit fix again, now 471

diff --git a/demo/Makefile b/demo/Makefile
--- a/demo/Makefile
+++ b/demo/Makefile
@@ -9,6 +9,9 @@ DOCKER_COMPOSE = $(DOCKER_COMPOSE_DEV)
 RUN_DEV = $(DOCKER_COMPOSE) run --rm texture-dev
 
 
+ARGS =
+
+
 show-user:
 	@echo "USERNAME=$(USERNAME)"
 	@echo "UID=$(UID)"
@@ -27,12 +30,31 @@ clean-dev:
 	$(RUN_DEV) rm -rf node_modules
 
 
-install:
-	$(RUN_DEV) npm ci
+.require-ARGS:
+	@if [ -z "$(ARGS)" ]; then \
+		echo "ARGS required"; \
+		exit 1; \
+	fi
+
+
+npm: .require-ARGS
+	$(RUN_DEV) npm $(ARGS)
+
+
+npm-audit:
+	$(RUN_DEV) npm audit $(ARGS)
+
+
+npm-ci:
+	$(RUN_DEV) npm ci $(ARGS)
+
+
+install-dependency: .require-ARGS
+	$(RUN_DEV) npm install $(ARGS)
 
 
 bundle:
-	$(RUN_DEV) npm run build
+	$(RUN_DEV) npm run build $(ARGS)
 
 
 start-dev:
